# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Surplus' do

pod 'Firebase', '>= 2.5.0'
pod 'DatePickerCell'
pod 'SwiftLoader'
pod 'Popover'
pod 'Google/CloudMessaging'
pod 'DZNEmptyDataSet'
pod 'AMScrollingNavbar', '~> 2.0.1'
pod 'JSQMessagesViewController'
pod 'EAIntroView', '~> 2.8.0'

end

target 'SurplusTests' do

end

target 'SurplusUITests' do

end

