# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Surplus' do

pod 'Venmo-iOS-SDK', '~>1.3'

end

target 'SurplusTests' do

end

target 'SurplusUITests' do

end

